### ISSUE TITLE
Platform Support

### ISSUE THREAD

**Issue by ozzyDev27** [Leg3ndary/APMC#1]
Does not render properly on Safari

**Comment by benz206** [comment]
![image](https://github.com/Leg3ndary/APMC/assets/57199957/15f208ef-9658-4d52-8674-e4e88d89dd2d)

Cannot replicate :/

**Comment by Ultra-bob** [comment]
can replicate on MacOS

https://github.com/Leg3ndary/APMC/assets/66791664/f589b16e-b34e-4fba-ab9f-71b7b6982b19

**Comment by benz206** [comment]
Believe it's been fixed, you can re-open if issue persists
